Integrated a EC2 instance health check using curl

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -289,6 +289,20 @@ aws_revoke:
     - apk add -no-cache openssh-client curl
   script:
   # starting health check for the EC2 Instance
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
-    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
+    - echo "Scanning for EC2 health using SSH connection..."
+    # attempting to curl EC2 instace 5 time with a 30 second delay...
+    - for i in {1...5}; do
+        echo "Attempt $i':' Checking if EC2 instance is healthy..."
+        if curl -s --connect-timeout 5 http://$EC2_HOST:80 | grep -q "200 OK" > /dev/null; then
+          echo "EC2 instance is healthy and responding to HTTP results"
+          exit 0
+        else
+          echo "EC2 instance is not responding yet. Retrying in 30 seconds..."
+          sleep 30 
+          fi
+          done
+          echo "EC2 instace failed health check after multiple attempts. Please investigate the issue."
+          exit 1
+        
+
+          
