fixes nginx

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,8 +2,8 @@ stages:
   - test
   - dockerize
   - deploy_test
-  - inspect_ec2
   - deploy
+  - inspect_ec2
 image: python:3.9-slim-bookworm
 
 variables:
@@ -46,36 +46,6 @@ test_deploy:
     - if [ -z "$EC2_HOST" ]; then echo "HOST is MISSING"; else echo "HOST is FOUND"; fi
     - echo "The value of HOST is [${EC2_HOST}]"
 
-
-inspect_ec2: 
-  stage: inspect_ec2
-  image: alpine:latest
-  script:
-    - apk add --no-cache openssh-client 
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
-    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
-    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
-    - |
-      ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
-        echo "[1]---- Checking if config file exists ----"
-        ls -l /etc/nginx/conf.d/default.conf || echo "default.conf MISSING"
-        ls -l /etc/nginx/conf.d/python_app.conf || echo "python_app.conf MISSING"
-
-        echo "[2]---- Printing the content of the config file ----"
-        sudo cat /etc/nginx/conf.d/default.conf 2>/dev/null|| echo "Config file not found"
-
-        echo "[3]---- Checking which config file is being used ----"
-        sudo nginx -T | grep -A 15 "server {" || echo "No server block found in nginx configuration"
-
-        echo "[4]---- Checking if nginx.conf is included in the conf.d----"
-        grep "include /etc/nginx/conf.d" /etc/nginx/nginx.conf
-
-        echo "[5] ---- checking for port 443 conflicts----"
-        sudo netstat -tulpn | grep LISTEN
-
-      EOF
-
 deploy_to_ec2:
   stage: deploy
   image: alpine:latest
@@ -104,7 +74,7 @@ deploy_to_ec2:
         fi 
 
        echo "#Adding Canonical to ssl Certificate"
-        sudo tee /etc/nginx/nginx.conf > /dev/null << 'CANONICAL'
+        sudo tee /etc/nginx/nginx.conf > /dev/null << CANONICAL
       user nginx;
       worker_processes auto;
       error_log /var/log/nginx/error.log notice;
@@ -155,4 +125,33 @@ deploy_to_ec2:
         sudo docker stop "$APP_NAME" || true
         sudo docker rm "$APP_NAME" || true
         sudo docker run -d --name "$APP_NAME" -p 127.0.0.1:5000:5000 "$IMAGE_NAME:$IMAGE_TAG"
+      EOF
+
+      inspect_ec2: 
+  stage: inspect_ec2
+  image: alpine:latest
+  script:
+    - apk add --no-cache openssh-client 
+    - eval $(ssh-agent -s)
+    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
+    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
+    - |
+      ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
+        echo "[1]---- Checking if config file exists ----"
+        ls -l /etc/nginx/conf.d/default.conf || echo "default.conf MISSING"
+        ls -l /etc/nginx/conf.d/python_app.conf || echo "python_app.conf MISSING"
+
+        echo "[2]---- Printing the content of the config file ----"
+        sudo cat /etc/nginx/conf.d/default.conf 2>/dev/null|| echo "Config file not found"
+
+        echo "[3]---- Checking which config file is being used ----"
+        sudo nginx -T | grep -A 15 "server {" || echo "No server block found in nginx configuration"
+
+        echo "[4]---- Checking if nginx.conf is included in the conf.d----"
+        grep "include /etc/nginx/conf.d" /etc/nginx/nginx.conf
+
+        echo "[5] ---- checking for port 443 conflicts----"
+        sudo netstat -tulpn | grep LISTEN
+
       EOF
