Fixing syntax

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -300,6 +300,6 @@ health_check:
           echo "EC2 instance is not responding yet. Retrying in 30 seconds..."
           sleep 30 
         fi
-      done
-      echo "EC2 instace failed health check after multiple attempts. Please investigate the issue."
-      exit 1
+        done
+        echo "EC2 instace failed health check after multiple attempts. Please investigate the issue."
+        exit 1
