added more echo

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -58,15 +58,23 @@ inspect_ec2:
     - mkdir -p ~/.ssh && chmod 700 ~/.ssh
     - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
     - |
-      ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
-        echo "---- Checking if config file exists ----"
-        ls -l /etc/nginx/conf.d/default.conf || echo "Config file not found"
-        echo "---- Printing the content of the config file ----"
-        sudo cat /etc/nginx/conf.d/default.conf || echo "Cannot read config file"
-        echo "---- Checking if nginx.conf is included in the conf.d----"
+      ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
+        echo "[1]---- Checking if config file exists ----"
+        ls -l /etc/nginx/conf.d/default.conf || echo "default.conf MISSING"
+        ls -l /etc/nginx/conf.d/python_app.conf || echo "python_app.conf MISSING"
+
+        echo "[2]---- Printing the content of the config file ----"
+        sudo cat /etc/nginx/conf.d/default.conf 2>/dev/null|| echo "Config file not found"
+
+        echo "[3]---- Checking which config file is being used ----"
+        sudo nginx -T | grep -A 15 "server {" || echo "No server block found in nginx configuration"
+
+        echo "[4]---- Checking if nginx.conf is included in the conf.d----"
         grep "include /etc/nginx/conf.d" /etc/nginx/nginx.conf
-        echo "---- checking for port 443 conflicts----"
+
+        echo "[5] ---- checking for port 443 conflicts----"
         sudo netstat -tulpn | grep LISTEN
+
       EOF
 
 deploy_to_ec2:
